export const GET_LOGIN = 'GET_LOGIN'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_FAILED = 'GET_LOGIN_FAILED'

export const GET_LOGOUT = 'GET_LOGOUT'
export const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS'
export const GET_LOGOUT_FAILED = 'GET_LOGOUT_FAILED'

export const GO_TO_DETAIL = 'GO_TO_DETAIL'
export const GO_TO_PROFILE = 'GO_TO_PROFILE'
export const GO_TO_LOGIN = 'GO_TO_LOGIN'

export const ROOT_NAV_BACK= 'ROOT_NAV_BACK'

export const NAVIGATION = {
  GETSTART_SCREEN: 'NAVIGATION/GETSTART_SCREEN',
  DETAIL_SCREEN: 'NAVIGATION/DETAIL_SCREEN',
  // LOGIN_SCREEN: 'NAVIGATION/LOGIN_SCREEN',
  // MAIN_TAB_SCREEN: 'NAVIGATION/MAIN_TAB_SCREEN',
  // BUYER_SCREEN: 'NAVIGATION/BUYER_SCREEN',
  // SELLER_SCREEN: 'NAVIGATION/SELLER_SCREEN',
  // REALTOR_SCREEN: 'NAVIGATION/REALTOR_SCREEN',
  // CHAT_SCREEN: 'NAVIGATION/CHAT_SCREEN',
  // ROOT_NAV_BACK: 'NAVIGATION/ROOT_NAV_BACK',
};
