export const GET_LOGIN = 'GET_LOGIN'
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_FAILED = 'GET_LOGIN_FAILED'

export const GET_LOGOUT = 'GET_LOGOUT'
export const GET_LOGOUT_SUCCESS = 'GET_LOGOUT_SUCCESS'
export const GET_LOGOUT_FAILED = 'GET_LOGOUT_FAILED'